USE BA_lexicon;

TRUNCATE TABLE lexicon_table_1;

INSERT INTO lexicon_table_1 (lexicon_number, lexicon_definition)
VALUES ('G1 Alpha', 'Α ἀ / ἄλφα of Hebrew origin; the first letter of the alphabet: figuratively only (from its use as a numeral) the first. Often used (usually “an”, before a vowel) also in composition (as a contraction from aneu (G427) in the sense of privation; so in many words beginning with this letter; occasionally in the sense of union (as a contraction of hama (G260): - Alpha (S) Christ is the Alpha to indicate that he is the beginning and the end (Th) ἄλφα, the first letter of the Greek alphabet. Ἄλφα, τό, indecl. (Rev.1:8,11; 21:6; 22:13). Alpha is used with the last letter of the Gr. alphabet (ōmega (G5598)) in the expression "alpha and omega, the first and the last," which is applied to God the Father or Christ (WSNT) Peculiar to Revelation, this expression is used by God for himself in 21:6 (cf. 22:13), and by Christ in 1:17 (cf. 2:8). Its use with “first and last” fixes its meaning: God begins and ends all things. While probably taken from Hellenistic speculation, perhaps by way of Palestinian Judaism, it derives its content from the OT. The link with “who is to come” gives it a new dynamic quality. “First and last” occurs in Isa.41:4 LXX; 44:6 MT; 48:12 MT; there are also Mandaean parallels. Number symbolism occurs in both rabbinic Judaism and Hellenism. The former uses the first and last letters of the alphabet to denote completeness, or with numbers for the sake of secrecy. The first letter alone stands for what is best. Truth has God’s seal because it consists of the first, middle, and last letters. In view of the link with “first and last” and the reference to Isa.44:6 (in the Hebrew rather than Greek text), Revelation probably took the expression from Palestinian Judaism. → prōtos (G4413), → eschatos (G2078) (KITTEL, Vol.I, pp.1–3)
As a numeral, ά = 1, α = 1000. The Hebrews, the Greeks, and the Romans all used their alphabetical letters as numerals, which accounts for the ease with which alpha and omega also represented first and last. (WSNT) As a prefix, it appears to have at least two and perhaps three distinct senses: [privative, copulative and intensive].... (A-S)
1. privative (στερητικόν), like the Lat. in-, the Eng. un-, giving a negative sense to the word to which it is preficed, as ἀβαρής; or signifying what is contrary to it as ἄτιμος, ἀτιμόω; before vowels generally ἀν-, as ἀναίτιος. (Th) ἀ- (before a vowel, ἀν-) negative, as in ἄ-γνωστος, ἄ-δικος (A-S) Negation or privation from ater (G817), apart from, without or aneu (G427), without. In such instances, a is called the alpha privative (e.g. asebēs (G765), ungodly, from the neg. a and sebomai (G4576), to worship; aoratos [from the priv. a and horatos (G3707), visible], invisible). When the priv. a is compounded with words which begin with a vowel, it frequently takes a n (nē), after it for the sake of euphony (e.g. anamartētos (G361), sinless). (WSNT) Negatives that are bound morphemes (e.g. α-privative in such words as ἄ-καρπος, -ov (un-fruitful); ἀ-θάνατος,-ov (im- mortal), and negative pronominal adjectives will be considered in other connections. (ibiblio.org)
( http://www.ibiblio.org/bgreek/project/funk-grammar/pre-alpha/lesson-41.html )

2. ἀ- copulative, indicating community and fellowship, as in ἁ-πλοῦς, ἀ-κολουθέω, ἀ-δελφός (A-S)
copulative (ἀθροιστικόν), akin to the particle ἅμα [cf. Curtis § 598], indicating community and fellowship, as in ἀδελφός, ἀκόλουθος. (Th) Collectiveness or assembling from hama (G260), same, together, with. The a then is

called collative (e.g., hapas (G537), everyone, from the collative a and pas (G3956), every; adelphos (G80), brother, from the collative a and delphos, a womb, or one who came from the same womb). (WSNT)
3. An intensive force (LS, s. α), as in ἀ-τενίζω is sometimes assumed.... (A-S) intensive (ἐπιτατικόν), strengthening the force of terms, like the Lat. con in composition; as ἀτενίζω from ἀτενής.... (Th) Intensity increasing the meaning of the simple word. In such a case, it is called an intens. or augmentative a (e.g. atenizō (G816), to look at intensely). This meaning is probably derived from agan (n.l.), very much, as in aganakteō (G23), to be indignant, from agan, very much, and achthos (n.l.), grief. (WSNT)
Observing the difference between prefixes ἀ and ου
￼It''s not as much in meaning as in grammar and function. α is the standard privative prefix that you can recognize in so many words of Greek origin. It is still productive in modern Greek (i.e. it can still be used to form new words) and it is used to "deprive" the word of whatever meaning its root has. So ἀ+θεός = someone who doesn''t have a god/doesn''t have a belief in a god. Ou is the equivalent of "non", so a word prefixed with it denotes a non-property. Ου in ancient Greek is a negative particle, so, unlike α (which has to be bound to a word) it can exist independently in a sentence to denote negation. This also means that it is not usually used as a prefix or compound and therefore is not as productive (if at all) as α. Ουτοπία is more like an expression that has been fused into a (compound) word: ου (no)+τόπος (place) = non-place (nonexistent place). Note, that the word was not actually coined in ancient Greek, but it seems to make its first appearance in Thomas More''s book with the same name, so its existence in Greek is called a "repatriated loan" (αντιδάνειο). [BMA]
*G ἆ ah, alas! Jgs 6:22(bis); JgsB 11:35(bis) exclamation expressing consternation on realizing one''s own terrifying predicament (M) [ABP cat. as οἴμμοι (G3629.3)]
*G ααρ אחר ''achêr (H311) = other; *Neh 7:33 Ναβι-ααρ Nabiar for MT אחר נבו nebô ''achêr (H5015, H312) the other Nebo (see also Neh.7:34) (LEH) [ABP cat. as ἕτερος (G2087)] Some codices, with two early printed editions, read אחד ''echad (H259) = “a certain,” instead of ''acher = another, or the other (rival). (Bullinger)
ְנבוֹ = nôb (H5011) ancient priestly city 1Sam.22:19 cf. v11... 21:2 ; 22:9 Νομβα, Νομμα, Νοβα , etc.; perhaps ֹנב nebô (q.v.) Ezr 2:29 = Neh7:33, Ezr 10:43, Ναβον, Ναβια, etc.; on Jerome’s identif. with Nobe near Lydda (BDB)'),
('G2 Aarōn', 'Ἀαρών = “light bringer” (BDB) Of Hebrew origin ַא ֲהרוֹן ahărôn (H175); Aaron, the brother of Moses (Th) - Ααρωνίδης,-ου,-ὁ (Apoc.) descendant of Aaron, Eleazar 4Mc 7:12 (DSG, M)'),
('G3 Abaddōn', 'Ἀβαδδών = “destruction” (Th)
Of Hebrew origin אבדּון ''ăbaddôn (H11); a destroying angel (NT) Intensively from אבד ''âbad (H6); abstractly a perishing; concretely Hades: - destruction (S) 1) ruin; 2) destruction; 3) the place of destruction; 4) the name of the angel-prince of the infernal regions, the minister of death and the author of havoc on the earth (Th) destruction; LXX ἀπώλεια (G684), only in Wisdom Lit., of the place of the ruined dead (Job 26:6; 28:22; 31:12, Ps.88:12, Prov.15:11*), indecl.; in NT, Abaddon, the angel of the Abyss: Rev.9:11. (A-S) [see apōleia (G684)] *G αβακ ה/בץ = the byssus, fine white linen 1Chr 4:21 (LEH) [ABP renders “families of Εφραδαβακ...” (no cat.)] ;bûts (H948) From an unused root (of the same form) meaning to bleach, that is, (intransitively) be white בּוּץ probably cotton (of some sort): - fine (white) linen (S) byssus, a costly, fine white linen cloth made in Egypt 1Chr.15:27; 2Chr.3:14; 5:12, Est.1:6, Ezk.27:15-16 [ABP renders βύσσινος (G1039)] (BDB) [compare βαδδιν (G897.1); ￼ βύσσος (G1040)] βαρ (G911.1); [G3.1] Abama Ἀβαμα / מהָּ בָּּ bâmâh = “high place” Αβαμα = ה/במה the cultic high place (interpreted as a toponym) Ezk 20:29 (bis) [see βωμός (G1041)] בּמה bâmâh (H1116, H1117) a place in Palestine (of places of idolatrous worship) (BDB) The same as ָּב ָּמה From bâmâh (H1116); Bamah, a place in Palestine. See also מותבּ bâmôth (H1120) (S) [compare στήλη (G4739.1)] Ezek.20:29 And  I said G2036  to  them, What  is  Abama,[G3.1] that  you  enter G1531  there? G1563  And they called upon G1941  its name, G3686 Abama,[G3.1] until G2193  today''s G4594  day. G2250 What is the high place - מה הבמה mah habbamah, “what is the high place?” What is it good for? Its being a high place shows it to be a place of idolatry. I called it במה bamah, to mark it with infamy; but ye continue to frequent it, even while it is called במה bamah, to the present day! (Clarke)'),
('G4 abarēs (not in LXX)', 'ἀβαρής,-ές not burdensome, not chargeable 2Cor.11:9 (Gr) From ἀ (G1) (as a negative particle) and baros (G922); weightless, that is (figuratively) not burdensome: - from being burdensome (S) 1) not burdensome; 2) not heavy; 3) light without weight (Th) easy, light in weight (ABP) not chargeable, 2Cor.11:9 (TSG) 2Cor.11:9 and being at hand G3918  with you,  and being lacking, G5302  I was not  lax G2655  of anyone. For my deficiencyG5303 the brethren G80 filled up in addition G4322   having come G2064  from  Macedonia; and in  everything G3956 I keptG5083 myself easy G4  to you,   and I will keep it so. G5083 From being burdensome (abarē). Old adjective, free from weight or light (a privative and baros, weight). See 1Th 2:9 for same idea. Paul kept himself independent (RWP) *G ἀβαρκηνιν (from Aram. ַב ְר ָּקן barqân (H1303)) the thorn bushes Jgs 8:7 [ABP cat. as ἄκανθα (G173)]; see βαρακηνιμ (Apoc.); βαρκοννιμ (Apoc.)'),
('G4.1 ἀβασίλευτος,-ος,-ον', 'without king Prv 30:27 (LEH) having no ruler: locusts... Cf. βασιλεύς (G935) (M) independent; not ruled by a king (ABP)'),
('G4.2 ἄβατος,-ος,-ον', 'untrodden Jb 38:27; inaccessible Est 8:12x; impassable Am 5:24; desolate Jer 6:8; not to be trodden 3Mc 5:43; ἄβατον (sc. γήν (G1093)) waste land, desert Jer 33(26):18; cpr. Lv 16:22; Jer 2:6; 12:10; 28(51):43 (LEH) to make c: pass., o dwelling-place, Jer 29:21. Cf. ἔρημος (G2048) (M)'),
('G4.3 ἀβατόω /ἀβατόομαι', 'to be laid waste Jer 30:14(49:20); neol. (LEH) to make impassible (ABP)'),
('G5 Abba Ἀββᾶ = “Father” (not in LXX)', 'Aram. ַא ָּבּא , emphatic form of אַב ''âb (H1) = Hebr. אָב, father) (A-S) of Chaldee origin אב; father (as a vocative) (S) Abba - (WH (-βά), Hebrew אבָּ father, in the Chaldean emphatic state, ַא ָּבא i.e. ὁ πατήρ (G3962), customary title used of God in prayer. Whenever it occurs in the NT it has the Greek interpretation subjoined to it, that is apparently to be explained by the fact that the Chaldee ַא ָּבא Abba through frequent use in prayer, gradually acquired the nature of a most sacred proper name, to which the Greek-speaking Jews added the appellative [name] from their own tongue (Th)')
